import React from "react";

export default function TermsOfUsePage() {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8 font-sans">
      <div className="max-w-4xl mx-auto bg-white rounded-2xl shadow-sm border border-gray-100 p-8 sm:p-12">
        <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-2">Terms of Use</h1>
        <p className="text-gray-500 mb-10">Last Updated: December, 2024</p>

        <div className="prose prose-blue max-w-none text-gray-700 space-y-6">
          <p>
            These Terms of Use and any terms incorporated herein (hereinafter, the “Terms”) apply to your (“user”, “you“) use of the Services, including https://changelly.com/ (“Website“), the technology and the platform integrated therein and any related applications (including without limitation the mobile one) associated therewith, which are operated and maintained by Marella LLC. and its affiliates (“Changelly”, “We”, or “Us”).
          </p>
          <p>
            We provide you with the possibility to use our Services as defined above on the following terms and conditions.
          </p>

          <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">1. Enforcement & Amendments</h2>
          <ul className="list-none space-y-4">
            <li><strong>1.1</strong> These Terms of Use constitutes a binding agreement between Changelly and the user as soon as the user visits the Website and uses Services. By doing so, the user confirms that he has read and accepted these Terms of Use in their entirety before finishing the registration procedure.</li>
            <li><strong>1.2</strong> The user accepts that Terms of Use may be updated by Changelly from time to time. If the user does not read and accept the Terms of Use in its entirety he should not use or continue using the Services.</li>
            <li><strong>1.3</strong> We reserve the right to alter, amend or modify these Terms from time to time, in our sole discretion. We will provide you with notice of such changes by sending an e-mail, providing notice on the homepage of the Website and/or by posting the amended Terms via our Website and updating the "Last Updated" date at the top of these Terms. The amended Terms will be deemed effective immediately upon posting on Website.</li>
          </ul>

          <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">2. Provided Services</h2>
          <ul className="list-none space-y-4">
            <li><strong>2.1</strong> Our Services provide you with the possibility to Exchange one type of crypto asset for another one, access to Marketplace, and access to the Decentralized Exchange of DeFi tokens. Terms of Use in regard to the Decentralized exchange on ChangellyDEX can be found at https://changelly.com/terms-of-use-dex.</li>
            <li><strong>2.2</strong> For the purposes hereof "Exchange" shall mean an exchange of the crypto asset of one type to the crypto asset of another type at the terms and conditions set forth by exchanging parties, which is executed via the Third-party service in respective block-chain network. When you exchange crypto assets you acknowledge and agree that the Exchange will be processed through the third-party exchange service with additional fees applicable to such Exchange. You acknowledge and agree that the exchange rates information made available via the Services are an estimation only and may differ from prevailing rates available via other sources outside of our Services.</li>
            <li><strong>2.3</strong> "Crypto Assets" herein shall be deemed as type of assets which can only and exclusively be transmitted by means of block-chain technology, including but not limited to digital coins and digital tokens and any other type of digital mediums of exchange, such as Bitcoin, Ethereum, Ripple, etc, to the full and absolute exempt of the securities of any kind.</li>
            <li><strong>2.4</strong> “Marketplace” herein shall mean an online digital aggregation platform for fiat providers with an option to compare current rates and limits for buying or selling crypto assets.</li>
            <li>
              <strong>2.5</strong> To be able to use all possibilities and functionality of our Services you shall go through the registration process and create a Changelly Account. "Changelly Account" is a user account accessible after the registration process and via the Services where the user may request to make a crypto assets exchange. User should manage and maintain only one Changelly Account. Users are prohibited from creating multiple accounts. When you create a Changelly Account you oblige to:
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li><strong>2.5.1</strong> change the password, which is generated by our Services automatically, for a strong password that you do not use for any other websites, online or off-line services;</li>
                <li><strong>2.5.2</strong> provide accurate e-mail, which actually belongs to you and shall be, therefore, verified. The access to the services provided by the Changelly without verification of the e-mail is not allowed;</li>
                <li><strong>2.5.3</strong> maintain the security of your Changelly Account and promptly notify us if you discover any suspicious activity related to your account;</li>
                <li><strong>2.5.4</strong> agree to receive emails containing information about credentials, passwords, transactions and marketing promotions;</li>
                <li><strong>2.5.5</strong> agree to pass through AML/KYC procedures, which may be applied to You according to our internal AML/KYC policies. As a part of such procedures, Changelly reserves the right to request additional information and documents, which are aimed without limitation to identify our user and to prove the source of the funds;</li>
                <li><strong>2.5.6</strong> take responsibility for all activities that occur under your Changelly Account.</li>
              </ul>
            </li>
            <li>
              <strong>2.6</strong> The "Floating exchange rate" option herein shall mean an exchange rate mode in which our platform does not guarantee the rate - so it fluctuates in accordance with the market. You acknowledge and agree that the exchange rate information made available via Services for the Floating exchange rate option is an estimation only and may differ from the actual rates available via other sources outside of our Services. Changelly cannot guarantee the execution of a Floating exchange rate transaction in some cases, including, but not limited to the following ones:
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li><strong>2.6.1</strong> user sent crypto assets to a previously used one-time address that had been generated for a Floating exchange rate transaction;</li>
                <li><strong>2.6.2</strong> user sent an amount of crypto assets different from the amount to be sent that was displayed on the Website, or did not account for the relevant withdrawal and network fees, thus sending an amount that is too small;</li>
                <li><strong>2.6.3</strong> the user sent crypto assets to a Changelly floating-rate address later than in 3 hours after the address was provided. Changelly floating rate addresses cannot be used after the 3 hour mark.</li>
                <li><strong>2.6.4</strong> in order to avoid any substantial losses for the customer caused by the rate change, when a significant disparity between an estimated exchange rate available on the Website and the rate received from a third-party exchange arises, a Floating exchange rate transaction may be failed automatically.</li>
              </ul>
            </li>
            <li>
              <strong>2.7</strong> When using the "Fixed exchange rate" option, your rate gets "locked" for fifteen or twenty minutes, meaning it remains the same irrespective of the changes on the market. You acknowledge and agree that for the Fixed exchange rate option the exchange rate information available on the Website may be different from the exchange rates for the Floating exchange rate option. Changelly cannot guarantee the execution of a Fixed exchange rate transaction in some cases, including, but not limited to the following ones:
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li><strong>2.7.1</strong> user sent crypto assets more than 15 minutes (20 minutes in case of BTC, XMR, LTC, DCR, EOS, GAS, BNB, VET) after clicking the “confirm & make payment” button when exchanging via the Fixed exchange rate option;</li>
                <li><strong>2.7.2</strong> user sent an amount of crypto assets different from the amount to be sent that was displayed on the Website, or did not account for the relevant withdrawal and network fees, thus sending an amount that is too small;</li>
                <li><strong>2.7.3</strong> user sent crypto assets to a previously used one-time address that had been generated for a Fixed exchange rate transaction.</li>
              </ul>
            </li>
            <li><strong>2.8</strong> In order to perform the Exchange via our Services, our system will automatically generate a particular address for the initiated transaction, which contains information about (i) the user; (ii) the crypto asset that user wants to exchange and the crypto asset that user wants to receive (jointly - "crypto pair"); and (iii) the recipient address provided by the user (the address where exchanged crypto assets will be deposited). The user understands that the crypto assets to be exchanged are transferred only to the particular address provided by the system. The address is active only for one transaction and particularly, the one designated by the system.</li>
            <li>
              <strong>2.9</strong> The technical issues arising from your misuse of our services, including but not limited to creating incorrect transactions, entering a wrong address both when indicating the recipient address and when sending your crypto assets to us, sending transactions through wrong chains, sending transactions without required Extra ID (Memo, Destination tag, etc) and other types of user mistakes may be resolved by our technical department with limitations. Upon successful resolution of a technical issue, the crypto assets sent incorrectly will be returned to the user, less all applicable fees.
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li><strong>2.9.1</strong> Changelly’s technical department is able to refund only BTC from the Segwit BTC address. No other crypto assets, including but not limited to, LTC, BSV, BCH sent to a Segwit BTC address could be refunded.</li>
                <li><strong>2.9.2</strong> Some types of cases require additional operating costs, therefore refunding/processing of certain incorrectly sent transactions will imply supplementary fees. These supplementary fees can be either extracted from the refund amount or can be sent by You to the fee collection address provided by our technical department.</li>
                <li><strong>2.9.3</strong> You hold Changelly harmless against any losses or damages arising from your misuse of our services and agree to pay the required refund fees, supplementary fees and operating costs, should these be applicable.</li>
              </ul>
            </li>
            <li><strong>2.10</strong> You acknowledge and agree that any refund may cause operating costs for the allocated resources required for resolving user issues arising from misuse of our services. Changelly shall be entitled to recover its operating costs for the services while executing any refund. In this case crypto assets will be refunded to the user, subtracting operating costs and network fees, only with a prior user’s consent.</li>
            <li><strong>2.11</strong> YOU INDEMNIFY AND HOLD CHANGELLY HARMLESS AGAINST ANY DIRECT, INDIRECT, CONSEQUENTIAL OR SPECIAL DAMAGES, OR ANY OTHER DAMAGES OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, LOSS OF USE, LOSS OF PROFITS OR LOSS OF DATA, WHETHER IN AN ACTION IN CONTRACT, TORT (INCLUDING BUT NOT LIMITED TO NEGLIGENCE) OR OTHERWISE, ARISING OUT OF OR IN ANY WAY CONNECTED WITH YOUR USE OF OUR SERVICES, INCLUDING BUT NOT LIMITED TO INCORRECT USE OF ADDRESS, INCORRECTLY CONSTRUCTED TRANSACTIONS ETC.</li>
            <li><strong>2.12</strong> Changelly does not provide custodial services, which means, we do not store your crypto assets on deposits and balances. In limited cases such as e.g. necessity to carry out AML/KYC procedure, your Exchange may be delayed. YOU HEREBY UNDERSTAND AND ACKNOWLEDGE, THAT ANY DELAYS ARE POSSIBLE; YOU INDEMNIFY AND HOLD US HARMLESS AGAINST ANY CLAIMS, DEMANDS AND DAMAGES, WHETHER DIRECT, INDIRECT, CONSEQUENTIAL OR SPECIAL, OR ANY OTHER DAMAGES OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, LOSS OF USE, LOSS OF PROFITS OR LOSS OF DATA, WHETHER IN AN ACTION IN CONTRACT, TORT (INCLUDING BUT NOT LIMITED TO NEGLIGENCE) OR OTHERWISE, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE EXCHANGE DELAY, WHETHER ORIGINATED FROM OUR FAULT OR NOT.</li>
            <li><strong>2.13</strong> Changelly is neither the creator, nor the administrator of any fiat provider at Marketplace. Therefore Changelly is not responsible for providing, setting or controlling the fees applicable to any of the services or products which you find and use via our Marketplace. It merely acts as an aggregator landing platform for the various fiat providers integrating APIs of those providers. All fiat trading capabilities and services take place in accordance with and are subject to the policies and terms of use of the said fiat provider.</li>
          </ul>

          <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">3. Fees</h2>
          <p>Changelly keeps its fee policy transparent. The current fee structure is two-layered and is comprised of exchange and network fees.</p>
          <ul className="list-none space-y-4">
            <li><strong>3.1.1</strong> The exchange fee is the amount charged by Changelly for executing transactions initiated by the users. The exchange fee structure depends on the transaction type: the Floating exchange rate or the Fixed one. The Floating exchange rate transactions incur a 0.25% fee from the output amount (it differs for transactions executed through our API partners). As with regard to the Fixed exchange rate transactions, Changelly finds the best rate available on the market and fixes it for the conversion in question; the respective rate is displayed to the user, thus guaranteeing the protection of users’ funds from market fluctuations during the exchange.</li>
            <li><strong>3.1.2</strong> The network fee is paid to cryptocurrency miners for processing transactions in the network, and it serves to ensure withdrawals of the funds from exchanges. Changelly collects and transfers these payments to respective exchanges, which themselves set the amount of the fee at any particular time. The moment a transaction is created, this fee is displayed to the user, with the amount being based on our estimates. With that, you acknowledge and agree that the final amount of the network fee charged can sometimes differ from our estimate. This occurs entirely due to the volatile nature of network fees prevalent on exchanges and does not depend on our platform in any respect.</li>
          </ul>

          <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">4. AML and KYC Procedure</h2>
          <ul className="list-none space-y-4">
            <li><strong>4.1</strong> In furtherance of the clause 2.5.5 Changelly reserves the right to apply the AML/KYC procedure to particular users, addresses and particular transactions of crypto assets.</li>
            <li><strong>4.2</strong> The up-to-date information on the AML/KYC procedures can always be found at AML/KYC.</li>
          </ul>

          <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">5. Eligibility</h2>
          <ul className="list-none space-y-4">
            <li>
              <strong>5.1</strong> Prior to your use of the Services and on an ongoing basis you represent, warrant, covenant and agree that:
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li><strong>5.1.1</strong> you use our Services at your sole option, discretion and risk;</li>
                <li><strong>5.1.2</strong> you are solely responsible for any applicable taxes which may be payable while using our Services;</li>
                <li><strong>5.1.3</strong> you are not located in, under the control of, or a national or resident of Afghanistan, Austria, Bangladesh, Crimea, Cuba, Donetsk People's Republic, Germany, Hong Kong SAR, India, Iran, Iraq, Japan, Luhansk People's Republic, North Korea, Syria, Turkey, United Kingdom, United States (including all territories), Venezuela, Yemen, or any jurisdiction where your use of the Services would violate applicable law ("Restricted Locations"). Changelly may restrict or deny services to any location at its discretion;</li>
                <li><strong>5.1.4</strong> you are at least 16 years old or of other legal age, according to your relevant jurisdiction;</li>
                <li><strong>5.1.5</strong> you agree to pay the fees for Exchanges completed via Services as defined by Changelly, which We may change from time to time; you also understand and acknowledge that network withdrawal fees are applicable to any types of withdrawals requested by you, the third party authorized by you, or under the request of a competent authority;</li>
                <li><strong>5.1.6</strong> there are risks, associated with Internet-based system, such as the failure of hardware, software, and Internet connections and with the Blockchain Protocol, such as any malfunction, unintended function, unexpected functioning of or attack on the Blockchain protocol;</li>
                <li><strong>5.1.7</strong> you guarantee that your crypto assets belong to you and they are not sold, encumbered, not in contention, or under seizure, and that neither exist any rights of third parties to your crypto assets;</li>
                <li><strong>5.1.8</strong> you shall provide correct information for constructing Exchange (e.g. payin and payout wallet address). Such wallet addresses shall not be associated with terrorism, fraudulent, scam or any type of illegal activity.</li>
              </ul>
            </li>
            <li>
              <strong>5.2</strong> You further represent, agree and warrant, that you will not violate any law, contract, third-party right or commit a tort by accessing or using the Services, and that you are solely responsible for your actions and/or inactions while using our Services. Without prejudice to the foregoing, you represent, agree and warrant, that YOU WILL NOT:
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li><strong>5.2.1</strong> use our Services or will immediately cease using those if any applicable law in your country prohibits or will prohibit you at any time from doing so;</li>
                <li><strong>5.2.2</strong> use our Services to participate in fraudulent, scam or any type of illegal activity;</li>
                <li><strong>5.2.3</strong> exchange via our Services or attempt to pay-in crypto assets, which are obtained from illegal gambling activities; fraud; money-laundering; or terrorist activities; or any other illegal activities. With our Services the user can only use crypto assets, which are obtained from legal sources;</li>
                <li><strong>5.2.4</strong> provide false, inaccurate, or misleading information;</li>
                <li><strong>5.2.5</strong> attempt to modify, decompile, reverse-engineer or disassemble our software in any way;</li>
                <li><strong>5.2.6</strong> use any robot, spider, crawler, scraper or other automated means or interface not provided by us to access the Services or to extract data;</li>
                <li><strong>5.2.7</strong> attempt to circumvent any content filtering techniques we employ, or attempt to access any service or area of our Services that you are not authorized to access;</li>
                <li><strong>5.2.8</strong> develop any third-party applications that interact with our Services without our prior written consent; AND</li>
                <li><strong>5.2.9</strong> Encourage or induce any third party to engage in any of the activities prohibited under this Section.</li>
              </ul>
            </li>
            <li><strong>5.3</strong> YOU INDEMNIFY AND HOLD US HARMLESS AGAINST ANY CLAIMS, DEMANDS AND DAMAGES, WHETHER DIRECT, INDIRECT, CONSEQUENTIAL OR SPECIAL, OR ANY OTHER DAMAGES OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, LOSS OF USE, LOSS OF PROFITS OR LOSS OF DATA OR LOSS OF ASSETS, WHETHER IN AN ACTION IN CONTRACT, TORT (INCLUDING BUT NOT LIMITED TO NEGLIGENCE) OR OTHERWISE, ORIGINATED FROM OR IN ANY WAY CONNECTED WITH INVALIDITY OR BREACH OF ANY OF THE PROVISIONS OF THIS SECTION AND THE ENTIRE TERMS.</li>
          </ul>

          <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">6. Information Privacy</h2>
          <ul className="list-none space-y-4">
            <li><strong>6.1</strong> Never share the details of your transaction, including, but not limited to, your Changelly ID, the transaction hash, recipient address and/or e-mail related to a Changelly account, with anyone except Changelly representatives. Changelly will not request specific information about user accounts, transactions or other personally identifiable data from you unless: (i) the information is requested to help complete a transaction initiated by you; (ii)the information is requested to efficiently process your enquiry; or (iii) it is legally required e.g. in connection with the AML/KYC procedure.</li>
            <li><strong>6.2</strong> You should ascertain that your transactions and/or account details are not disclosed by ensuring that you do not knowingly or accidentally share, provide or facilitate unauthorized use of it.</li>
            <li><strong>6.3</strong> WITHOUT LIMITING THE FOREGOING, CHANGELLY SHALL NOT BE LIABLE FOR ANY LOSSES OR DAMAGES INCURRED AS A RESULT OF ANY INFORMATION SUBMITTED TO IT THROUGH THIS WEBSITE OR ANY CONTACT E-MAIL THEREOF OR FOR ITS TRANSMISSION OF INFORMATION TO ANY PERSON(S) OR ENTITY(IES) AS A RESULT OF A REQUEST FOR SUCH TRANSMISSION REASONABLY BELIEVED BY CHANGELLY TO HAVE BEEN MADE BY SUCH PERSON OR ENTITY.</li>
          </ul>

          <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">7. Risk Disclosure</h2>
          <ul className="list-none space-y-4">
            <li><strong>7.1</strong> Changelly does not and will not provide any investment advice or legal advice regarding your exchange. You acknowledge that only you are responsible for your decisions and actions performed on our platform and we will not make any personal recommendations for or advise you on the exchange of particular crypto assets. Before performing any exchange of crypto assets, you should carefully consider whether such an exchange is suitable for you with your current circumstances and financial resources.</li>
            <li><strong>7.2</strong> Be aware that crypto assets are generally assumed to be subject to high volatility due to them still being in the early stages of developing, technologically and financially. Crypto assets do not necessarily have a specific form of protection or regulation by any governmental body, which means that by exchanging crypto assets, you will not be able to enforce any guarantees or safeguards expected with regulated financial services.</li>
            <li><strong>7.3</strong> THE RISK OF LOSS IN THE EXCHANGE OF CRYPTO ASSETS CAN BE SUBSTANTIAL, AND THEREFORE YOU SHOULD UNDERSTAND THE POSSIBILITY OF LOSSES ASSOCIATED WITH THE EXCHANGE OF CRYPTO ASSETS AND MUST ASSUME RESPONSIBILITY FOR ALL THE RISKS ASSOCIATED WITH SUCH EXCHANGES AND FOR THEIR RESULTS.</li>
          </ul>

          <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">8. Third-Party Content and Services</h2>
          <ul className="list-none space-y-4">
            <li><strong>8.1</strong> For the purposes hereof "Third-Party Content" shall mean the content provided by third parties, including without limitation links to web pages of such parties, which may be represented on the Website and other Services. At the same time "Third-party service" refers to any platform or network in which crypto assets belong to you or where you are the beneficial owner of crypto assets; or any website or platform which we redirect you to; and this platform or website is maintained by a third party outside of the Services, including, but not limited to third-party accounts.</li>
            <li><strong>8.2</strong> Price accuracy. Although we enforce strict price accuracy policies for all fiat providers and do our best to ensure that the content displayed on or via our Marketplace is up-to-date and accurate, we cannot guarantee the reliability or accuracy of such content.</li>
            <li><strong>8.3</strong> No control over third-party services. If you encounter any problems with any Third-Party Services available via Changelly, you acknowledge that you should resolve that issue with the relevant third-party or fiat provider and that your sole remedy in such circumstances lies within the relevant third-party and not within Changelly.</li>
            <li><strong>8.4</strong> You may be charged fees by the third-party service provider. Changelly is not responsible for any third-party services' fees. You are solely responsible for your use of the third-party service, and you agree to comply with all terms and conditions applicable to any third-party service.</li>
            <li><strong>8.5</strong> The exchange rates discrepancy is at any time possible due to the Third-Party algorithms. YOU INDEMNIFY AND HOLD CHANGELLY HARMLESS AGAINST ANY DIRECT, INDIRECT, CONSEQUENTIAL OR SPECIAL DAMAGES, OR ANY OTHER DAMAGES OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, LOSS OF USE, LOSS OF PROFITS OR LOSS OF DATA, WHETHER IN AN ACTION IN CONTRACT, TORT (INCLUDING BUT NOT LIMITED TO NEGLIGENCE) OR OTHERWISE, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE AFORESAID EXCHANGE RATES DISCREPANCY WHICH IS BELOW 10 USD.</li>
            <li><strong>8.6</strong> While using our Services, you may view Third-Party Content. We do not control, endorse or adopt (unless otherwise expressly stated by Us) any Third-Party Content and shall have no responsibility for Third-Party Content, including without limitation material that may be misleading, incomplete, erroneous, offensive, indecent or otherwise objectionable. In addition, your business dealings or correspondence with such third parties are solely between you and the third parties. We are not responsible or liable for any loss or damage of any sort incurred as the result of any such dealings, and you understand that your use of Third-Party Content, and your interactions with third parties, is at your own risk.</li>
          </ul>

          <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">9. Intellectual Property</h2>
          <ul className="list-none space-y-4">
            <li><strong>9.1</strong> All our intellectual property assets ("IP") including but not limited to all copyrights, trademarks, patents, service marks, trade names, software code, icons, logos, characters, layouts, trade secrets, buttons, color scheme and graphics are protected by local and international intellectual property laws and treaties.</li>
            <li><strong>9.2</strong> We hereby grant you a limited, nonexclusive and non-sublicensable license to access and use our IP for your personal use only.</li>
            <li><strong>9.3</strong> In any case you may not alter, modify, reproduce, distribute or commercially exploit any materials, including text, graphics, video, audio, software code, user interface design or logos.</li>
            <li><strong>9.4</strong> The license granted under this Section will automatically terminate if We suspend or terminate your access to the Services</li>
            <li><strong>9.5</strong> In case you upload or share any feedback, suggestion, idea or other information or material ("Content") with us you automatically grant us a worldwide license to use your content. It becomes part of the public domain as long as it remains on our Website and Services. It can be used for marketing or any other purposes at our sole discretion.</li>
          </ul>

          <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">10. Communications</h2>
          <p>You agree and consent to receive electronically all Communications, that Changelly may be willing to communicate to you in connection with your Changelly Account and/or use of our Services. For the purposes hereof “Communications” shall mean all and any communication, agreement, document, receipt, notice and disclosure, which may be from time to time addressed to user by Changelly. You may withdraw your consent to receive electronic Communications by sending a withdrawal notice to support. If this is a case you waive your right to plead ignorance. If you decline or withdraw consent to receive electronic Communications, Changelly may suspend or terminate your use of the Services.</p>

          <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">11. Limitation of Liabilities</h2>
          <ul className="list-none space-y-4">
            <li><strong>11.1</strong> Except as expressly provided to the contrary in a writing by Us, our Services are provided on an "As is" and "As available" basis. WE EXPRESSLY DISCLAIM, AND YOU WAIVE, ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT AS TO OUR SERVICES, INCLUDING THE INFORMATION, CONTENT AND MATERIALS CONTAINED THEREIN.</li>
            <li><strong>11.2</strong> Except as otherwise required by law, IN NO EVENT SHALL CHANGELLY, OUR DIRECTORS, OFFICERS, MEMBERS, EMPLOYEES OR AGENTS BE LIABLE FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL OR SPECIAL DAMAGES, OR ANY OTHER DAMAGES OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, LOSS OF USE, LOSS OF PROFITS OR LOSS OF DATA, WHETHER IN AN ACTION IN CONTRACT, TORT (INCLUDING BUT NOT LIMITED TO NEGLIGENCE) OR OTHERWISE, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OF OR INABILITY TO USE OUR SERVICES, INCLUDING WITHOUT LIMITATION ANY DAMAGES CAUSED BY OR RESULTING FROM RELIANCE BY ANY USER ON ANY INFORMATION OBTAINED FROM CHANGELLY, OR THAT RESULT FROM MISTAKES, OMISSIONS, INTERRUPTIONS, DELETION OF FILES OR EMAIL, ERRORS, DEFECTS, VIRUSES, DELAYS IN OPERATION OR TRANSMISSION OR ANY FAILURE OF PERFORMANCE, WHETHER OR NOT RESULTING FROM A FORCE MAJEURE EVENT, COMMUNICATIONS FAILURE, THEFT, DESTRUCTION OR UNAUTHORIZED ACCESS TO CHANGELLY'S RECORDS, PROGRAMS OR SERVICES.</li>
            <li><strong>11.3</strong> Exchanges via our Services cannot be canceled by Changelly. Therefore, check the details of your exchange details before making such exchange. Changelly is not responsible for your crypto assets once they have been sent outside of the Services. Moreover, Changelly doesn’t guarantee the uptime of the exchange.</li>
            <li><strong>11.4</strong> To the maximum extent permitted by applicable law, IN NO EVENT SHALL THE AGGREGATE LIABILITY OF CHANGELLY (INCLUDING OUR DIRECTORS, OFFICERS, MEMBERS, EMPLOYEES AND AGENTS), WHETHER IN CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE, WHETHER ACTIVE, PASSIVE OR IMPUTED), PRODUCT LIABILITY, STRICT LIABILITY OR OTHER THEORY, ARISING OUT OF OR RELATING TO THE USE OF, OR INABILITY TO USE, CHANGELLY OR TO THESE TERMS EXCEED THE FEES PAID BY YOU TO CHANGELLY WITHIN 3 MONTHS IMMEDIATELY PRECEDING THE DATE OF ANY CLAIM GIVING RISE TO SUCH LIABILITY.</li>
            <li><strong>11.5</strong> We strive to protect our users from fraudulent and scam activities in the sphere of crypto assets. It is possible, that some crypto assets are purposed for unlawful seizure of the property, or are construed as a fraud, scam or any other activity, recognized by the laws as illegal and/or non-compliant with legal requirements. Changelly cooperates with law enforcements agencies and other competent authorities in order to determine and disclose such crypto assets. We reserve the right to prohibit and discontinue any Exchanges via our Services with such crypto asset at our sole discretion, without any prior notice to you and without publication of the reason for such decision, whenever this comes to our knowledge. YOU INDEMNIFY AND HOLD CHANGELLY HARMLESS AGAINST ANY CLAIMS, DEMANDS AND DAMAGES, WHETHER DIRECT, INDIRECT, CONSEQUENTIAL OR SPECIAL, OR ANY OTHER DAMAGES OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, LOSS OF USE, LOSS OF PROFITS OR LOSS OF DATA, WHETHER IN AN ACTION IN CONTRACT, TORT (INCLUDING BUT NOT LIMITED TO NEGLIGENCE) OR OTHERWISE, ORIGINATED FROM OR IN ANY WAY CONNECTED WITH PROHIBITION AND DISCONTINUATION OF EXCHANGES IN OUR WEBSITE WITH ANY CRYPTO ASSET.</li>
            <li><strong>11.6</strong> Information regarding the current operational status of the Services, including the availability of specific Crypto Assets for Exchange and the status of the API, may be published at https://changelly.com/status (the "Status Page"). The Status Page is provided for informational purposes only. Changelly does not warrant the accuracy, completeness, or timeliness of the information displayed on the Status Page and assumes no obligation to update it in real time. Users are encouraged to consult the Status Page prior to initiating any Exchange. The availability or non-availability of information on the Status Page does not affect Changelly's rights under Sections 11.3 and 11.5 of these Terms.</li>
          </ul>

          <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">12. No Offer of Securities</h2>
          <ul className="list-none space-y-4">
            <li><strong>12.1</strong> Changelly takes all possible measures to integrate and exchange those digital coins and digital tokens and other types of digital mediums of exchange only that cannot be classified as “security“ by SEC or other competent national authorities.</li>
            <li><strong>12.2</strong> The responsibility for the fact that the crypto asset cannot be treated as “security“ lies with the owner of digital token and/or digital coin. Changelly reserves the right at its sole discretion to prohibit and discontinue any exchanges (as well as any other type of transaction) with the token or the coin if there is any risk or speculations that such token and/or coin can be treated as “security“.</li>
            <li><strong>12.3</strong> We follow the best practices to decide whether crypto assets are security or not. However, for the avoidance of any doubt the provisions of this clause shall not constitute or deemed to be construed to constitute any warranty and/or investment, financial, legal or any other professional advice, that any crypto asset that any crypto asset available through our Services is not a security.</li>
          </ul>

          <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">13. Termination of the Terms</h2>
          <ul className="list-none space-y-4">
            <li>
              <strong>13.1</strong> We reserve the right to terminate these Terms and delete your Changelly Account and registration (including your username and password) in the following cases:
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li><strong>13.1.1</strong> If for any reason We decide to discontinue to provide the Service, by providing at least a 3 (three) calendar days’ notice (which shall be provided by e-mail);</li>
                <li><strong>13.1.2</strong> If We believe that you have breached any of the terms of these Terms, immediately without notice;</li>
                <li><strong>13.1.3</strong> If We decide to terminate our Services, immediately without notice.</li>
              </ul>
            </li>
            <li><strong>13.2</strong> Changelly may suspend or terminate your account or use of the Services, or the processing of any crypto asset transaction, at any time if it determines in its sole discretion that you are accessing the Services from a Restricted Location or are a resident of one (see cl.5.1.3. of our Terms of Use).</li>
          </ul>

          <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">14. Applicable Law; Arbitration</h2>
          <ul className="list-none space-y-4">
            <li><strong>14.1</strong> You and Changelly agree to arbitrate any dispute arising from these Terms or your use of the services, including disputes in which either party seeks equitable and other relief for the alleged unlawful use of copyrights, trademarks, trade names, logos, trade secrets or patents.</li>
            <li><strong>14.2</strong> You and Changelly agree to notify each other in writing of any dispute within 30 days of when it arises. Notice to Changelly must be sent to legal@changelly.com.</li>
            <li>
              <strong>14.3</strong> You and Changelly further agree:
              <ul className="list-[lower-alpha] pl-5 mt-2 space-y-1">
                <li>(a) to attempt informal resolution prior to any demand for arbitration;</li>
                <li>(b) that arbitration will be conducted confidentially by a single arbitrator in accordance with the laws of the St.Vincent and Grenadines.</li>
              </ul>
            </li>
            <li><strong>14.4</strong> Any dispute between the parties will be governed by these Terms and the laws of the St.Vincent and Grenadines, without giving effect to any conflict of laws principles that may provide for the application of the law of another jurisdiction. Whether the dispute is heard in arbitration or in court, you will not commence against Changelly a class action, class arbitration, or representative action or proceeding.</li>
          </ul>

          <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">15. Miscellaneous</h2>
          <ul className="list-none space-y-4">
            <li><strong>15.1</strong> These Terms contain the entire agreement, and supersede all prior and contemporaneous understandings between the parties regarding the Services.</li>
            <li><strong>15.2</strong> In the event of any conflict between these Terms and any other agreement you may have with Changelly, the terms of that other agreement will prevail only if these Terms are specifically identified and declared to be overridden by such other agreement.</li>
            <li><strong>15.3</strong> Our failure or delay in exercising any right, power or privilege under these Terms shall not operate as a waiver thereof.</li>
            <li><strong>15.4</strong> The invalidity or unenforceability of any of these Terms shall not affect the validity or enforceability of any other of these Terms, all of which shall remain in full force and effect.</li>
            <li><strong>15.5</strong> You may not assign or transfer any of your rights or obligations under these Terms without prior written consent from Changelly, including by operation of law or in connection with any change of control. Changelly may assign or transfer any or all of its rights under these Terms, in whole or in part, without obtaining your consent or approval.</li>
          </ul>

        </div>
      </div>
    </div>
  );
}
